baseURL: https://palant.info/
languageCode: en-us
copyright: This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.
title: "Extensions, security, random blah blah"
params:
  AuthorTwitter: "@WPalant"
author:
  name: Wladimir Palant

taxonomies:
  category: categories

enableRobotsTXT: true
pygmentsUseClasses: true

permalinks:
  articles: /:year/:month/:day/:slug/
  projects: /:year/:month/:day/:slug/

outputFormats:
  MozillaRSS:
    baseName: pmo
    isPlainText: true
    mediaType: application/rss+xml
  HTML:
    isHTML: false

outputs:
  home:
    - HTML
    - JSON
    - RSS
    - MozillaRSS

menu:
  main:
    - Name: Home
      URL: /
      Weight: 1
    - Name: Articles
      URL: /articles/
      Weight: 2

markup:
  goldmark:
    extensions:
      linkify: false
    parser:
      autoHeadingIDType: blackfriday
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 8
